name: Publish nuget packages

on:
  workflow_dispatch:
  push:
    paths:
      - "SimplePlugin/**.csproj"
      - "SimplePlugin.Generator/**.csproj"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # Enable OIDC for package publishing
    permissions:
      id-token: write
      contents: read
    
    strategy:
      matrix:
        projectName: [ SimplePlugin, SimplePlugin.Generator ]
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      # Setup dotnet 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0
      
      # Login into NuGet
      - name: NuGet Login
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{ secrets.NUGET_USERNAME }}
      
      # Run the publishing action
      - name: Publish on version change
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: ${{ matrix.projectName }}/${{ matrix.projectName }}.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}